### ISSUE TITLE
Media queries movile

### ISSUE THREAD

**Issue by AgustinTorresOlivera** [MarcosFlores178/mercado_liebre_dh#1]
![image](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/129790464/60bf80ac-cea4-4cbc-8524-04da80dbd51a)
Como se vera cuando entro a movile se queda asi y deberia quedar algo como esto 
![image](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/129790464/a590eda9-8d19-42e0-bca6-95756e08e32a)
Esconder lo que dice Ofertas,Tiendas Oficiales,Vender, Ayuda, etc

**Comment by MarcosFlores178** [comment]
El corte del media query está correcto. La versión mobile tiene techo superior en 360px.
![Captura de pantalla 2024-07-02 212640](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/b2a018ac-cb3d-4b4a-9a47-4d3367ad9ac6)
![Captura de pantalla 2024-07-02 212805](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/4f3a00f5-d24a-4966-8396-0da398e9b297)
