### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by AgustinTorresOlivera** [MarcosFlores178/mercado_liebre_dh#2]
![image](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/129790464/777a171c-2f9b-4607-82d6-e0231e39b2d4)
como se ve tienes dos imagenes envez de una como deberia ser para el apartado movile, deberia de quedar algo tipo tal que asi 
![image](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/129790464/de94e983-5caa-4851-ab10-779edbe83857)

**Comment by MarcosFlores178** [comment]
El corte de mobile es correcto, 360px y se ve 1 columna de imagenes. En tablets se ven 2 columnas de imagenes y en desktop se ven 4. 
![Captura de pantalla 2024-07-02 212805](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/c675c0e3-0c2e-4fb5-8ea8-564a64834571)
![Captura de pantalla 2024-07-02 213335](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/336deeca-5a22-43a9-941e-72132bceaa23)
