### ISSUE TITLE
En general

### ISSUE THREAD

**Issue by AgustinTorresOlivera** [MarcosFlores178/mercado_liebre_dh#3]
- [ ] 1 no cumple (El header en movile no esconde los iconos y los cambia por el menu hamburguesa).
- [ ] 2 no cumple (El main esta con dos articulos en vez de 1 en movile).
- [x] 3 cumple  (el footer esta perfecto).
- [x] 4 cumple  (Tiene formulario login y register y cumple con lo responsive).
- [x] 5 cumple  (El header para desktop esta perfecto).

**Comment by MarcosFlores178** [comment]
El corte en mobile está correcto.
![Captura de pantalla 2024-07-02 212640](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/4ace3e1d-555a-4f70-ae83-426572a084d6)
![Captura de pantalla 2024-07-02 212805](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/84918791-5ce0-4e30-8122-1ce0933639e8)
![Captura de pantalla 2024-07-02 213335](https://github.com/MarcosFlores178/mercado_liebre_dh/assets/85637009/6c1defd1-324b-4e92-9290-b4342eabf61a)
